name: Prueba de ejecucion de Script
run-name: Script de Python en Ubuntu
on: [push]
jobs:
  ejecuta-script-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4GIT
      - name: Inicia Actions
        run: echo "Inicia Actions"
      - name: Listar archivos
        run: ls -al
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Ejecutar script de Python
        run: python app.py