name: Prueba ejecución de Python
run-name: ${{ github.actor }} is testing out Python Script on Ubuntu 🚀

on: [push]

jobs:
  execute-python-script:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Este workflow ejecutará un script de Python."
      - run: echo "Inicia actions"
      - name: Check out repository code
        uses: actions/checkout@v6
      - run: python --version
      - run: ls -al
      - run: python app.py